### ISSUE TITLE
Update example work with SDK 0.44.x

### ISSUE THREAD

**Issue by atmoner** [chainapsis/keplr-example#18]
Hello!
Since updating the sdk from cosmos 0.44.x, your example no longer works, so I updated it.
I added the proto and stargate lib of cosmJs and adapted the `connectWithSigner()` function.

If that can help! I can do a clean pull request with atom data.

Check this commit: https://github.com/atmoner/keplr-example/commit/7ba6888d040a373d8f68d0ba032ef7a4135af814

Best regards, 
atmon3r | BitCanna

**Comment by daniel-farina** [comment]
@atmoner 
I just tested your changes and they are working well. Would you mind submitting a PR?  I can also submit one if you don't have time right now. Just let me know.

Thanks!
